// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { CardInstanceId } from "./CardInstanceId";

export type CardInstance = { id: CardInstanceId, card: CardId, };
