// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { CardKind } from "./CardKind";
import type { Condition } from "./Condition";
import type { Effect } from "./Effect";
import type { Tag } from "./Tag";

export type CardDef = { id: CardId, 
/**
 * 作者データの長さ上限。docs/design/cross-cutting.md「自由入力(UGC)の取り扱い」
 * §3、domain-model.md「作者データへのBoundedString適用」参照。
 */
name: string, kind: CardKind, text: string, tags: Array<Tag>, effects: Array<Effect>, requires: Array<Condition>, };
