// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDef } from "./CardDef";
import type { CardId } from "./CardId";
import type { CharacterId } from "./CharacterId";
import type { StatId } from "./StatId";

export type Character = { id: CharacterId, name: string, stats: { [key in StatId]: number }, deck: Array<CardId>, 
/**
 * 持ち帰ったカードのCardDef凍結コピー(domain-model.md「セッション終了処理
 * (finalize)」)。CardIdはそのシナリオ内でしか解決できないため、参照ではなく
 * 値そのものを持つ(2026-07-20決定)。`#[serde(default)]`は、この
 * フィールド追加前に保存されたパーティファイル・fixtureを空Vecとして
 * 読めるようにするため(後方互換)。
 */
owned_cards: Array<CardDef>, };
