// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { CharacterId } from "./CharacterId";
import type { StatId } from "./StatId";

export type Character = { id: CharacterId, name: string, stats: { [key in StatId]: number }, deck: Array<CardId>, };
