// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardInstanceId } from "./CardInstanceId";
import type { Character } from "./Character";
import type { CharacterId } from "./CharacterId";
import type { Outcome } from "./Outcome";
import type { ProposalId } from "./ProposalId";
import type { Scenario } from "./Scenario";
import type { ScenarioPatch } from "./ScenarioPatch";
import type { SceneId } from "./SceneId";

export type Command = { "StartSession": { scenario: Scenario, party: Array<Character>, } } | { "PlayCard": { by: CharacterId, card: CardInstanceId, free_text: string | null, } } | { "Propose": { by: CharacterId, text: string, } } | { "ApplyPatch": { patch: ScenarioPatch, } } | { "JudgeProposal": { proposal: ProposalId, accepted: boolean, } } | { "GmAdvance": { to: SceneId, } } | { "EndSession": { outcome: Outcome, } };
