// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { StatId } from "./StatId";

/**
 * アクターの手札 or table に存在するかで判定する(FlagIsはv0.2で廃止。
 * docs/design/domain-model.md参照)。
 */
export type Condition = { "HasCard": CardId } | { "StatAtLeast": [StatId, number] };
