// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { Target } from "./Target";

/**
 * シーン入場時に配るカード。
 */
export type Deal = { card: CardId, to: Target, };
