// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { Outcome } from "./Outcome";
import type { SceneId } from "./SceneId";
import type { StatId } from "./StatId";
import type { Target } from "./Target";

export type Effect = { "GotoScene": SceneId } | "AdvancePhase" | { "DealCard": { card: CardId, to: Target, } } | { "ModifyStat": { target: Target, stat: StatId, delta: number, } } | { "EndSession": Outcome };
