// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDef } from "./CardDef";
import type { CardId } from "./CardId";
import type { CardInstanceId } from "./CardInstanceId";
import type { Character } from "./Character";
import type { CharacterId } from "./CharacterId";
import type { Effect } from "./Effect";
import type { Outcome } from "./Outcome";
import type { Phase } from "./Phase";
import type { ProposalId } from "./ProposalId";
import type { RemovalReason } from "./RemovalReason";
import type { Role } from "./Role";
import type { ScenarioPatch } from "./ScenarioPatch";
import type { ScenarioSnapshot } from "./ScenarioSnapshot";
import type { SceneId } from "./SceneId";
import type { UserId } from "./UserId";

export type Event = { "SessionStarted": { scenario: ScenarioSnapshot, party: Array<Character>, roles: { [key in UserId]: Role }, initial_phase: Phase, initial_scene: SceneId, } } | { "SceneEntered": { scene: SceneId, narration: string, 
/**
 * このシーンの`scene_def.deals`から実際に配ったカードの一覧
 * (カード効果由来の`DealCard`は含まない)。domain-model.md
 * 「カードの消費・除去」参照。`#[serde(default)]`は、この
 * フィールド追加前に記録されたfixtureを空Vecとして読める
 * ようにするため(後方互換)。
 */
local_instances: Array<CardInstanceId>, } } | { "CardDealt": { to: CharacterId, card: CardId, instance: CardInstanceId, } } | { "CardPlayed": { by: CharacterId, card: CardId, free_text: string | null, } } | { "CardRemoved": { from: CharacterId, card: CardId, instance: CardInstanceId, reason: RemovalReason, } } | { "EffectApplied": { effect: Effect, } } | { "PhaseAdvanced": { phase: Phase, } } | { "ProposalSubmitted": { id: ProposalId, by: CharacterId, text: string, } } | { "ScenarioPatched": { patch: ScenarioPatch, } } | { "ProposalJudged": { id: ProposalId, accepted: boolean, } } | { "SessionEnded": { outcome: Outcome, } } | { "RewardsGranted": { to: CharacterId, cards: Array<CardDef>, } } | { "CardsDiscarded": { from: CharacterId, cards: Array<CardId>, } };
