// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardId } from "./CardId";
import type { SceneId } from "./SceneId";

/**
 * 検査で見つかった問題。docs/design/scenario-lint.md「検査項目と重大度」の表に対応。
 */
export type LintIssue = { "DuplicateCardId": CardId } | { "DuplicateSceneId": SceneId } | { "UnknownCardId": CardId } | { "UnknownSceneId": SceneId } | "CharacterTargetInScenarioData" | "NoInitialScene" | { "UnreachableScene": SceneId } | { "DeadEndScene": SceneId };
