// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LintIssue } from "./LintIssue";
import type { Severity } from "./Severity";

/**
 * `severity`は`issue.severity()`から導出可能な値であり、両者が矛盾する
 * インスタンスも型上は構築できてしまう(deriveされた`Deserialize`は
 * この不変条件を検証しない)。そのため外部入力(wasm境界越しのJSON等)を
 * この型へ直接デコードしない。境界を越えたJSONは常に`lint()`が生成した
 * ものをTS側が読むだけの用途に限る。
 */
export type LintFinding = { severity: Severity, issue: LintIssue, };
