// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * セッションの結末。勝利/敗北カードの選択で分岐する(domain-model.md参照)。
 */
export type Outcome = "Victory" | "Defeat";
