// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDef } from "./CardDef";
import type { CardId } from "./CardId";
import type { Phase } from "./Phase";
import type { SceneDef } from "./SceneDef";
import type { SceneId } from "./SceneId";
import type { Target } from "./Target";
import type { Transition } from "./Transition";

export type PatchOp = { "AddCardDef": CardDef } | { "ReplaceScene": SceneDef } | { "AddScene": { phase: Phase, scene: SceneDef, } } | { "AddTransition": { scene: SceneId, transition: Transition, } } | { "DealCard": { card: CardId, to: Target, } };
