// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * validateの拒否理由。tabifuda-coreの公開APIはpanicしない(CLAUDE.md規約)。
 */
export type PatchError = "DuplicateCardId" | "DuplicateSceneId" | "SceneNotFound" | "PhaseNotFound" | "CardNotFound";
