// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";
import type { SceneDef } from "./SceneDef";

export type PhaseDef = { phase: Phase, scenes: Array<SceneDef>, };
