// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterId } from "./CharacterId";
import type { ProposalId } from "./ProposalId";

export type Proposal = { id: ProposalId, by: CharacterId, text: string, };
