// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Event::CardRemoved`の理由。domain-model.md「カードの消費・除去」参照。
 */
export type RemovalReason = "Consumed" | "SceneLeft";
