// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchError } from "./PatchError";

export type RuleError = "Forbidden" | "NoActiveSession" | "SessionAlreadyStarted" | "SessionEnded" | "SessionPaused" | "SessionNotPaused" | "ScenarioHasNoScenes" | "CardNotFound" | "ConditionNotMet" | "SceneNotFound" | "NoNextPhase" | "ProposalNotFound" | { "InvalidPatch": PatchError };
