// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioId } from "./ScenarioId";

export type ScenarioMeta = { id: ScenarioId, title: string, author: string, forked_from: ScenarioId | null, };
