// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioId } from "./ScenarioId";

export type ScenarioMeta = { id: ScenarioId, title: string, author: string, 
/**
 * 依頼選択画面向けの概要(1〜2行)。domain-model.md「文字列の長さ上限」参照。
 */
summary: string, forked_from: ScenarioId | null, };
