// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchOp } from "./PatchOp";

export type ScenarioPatch = { ops: Array<PatchOp>, 
/**
 * GMのコメント。ログカードとして表示(cross-cutting.md §UGC-3、C4で導入)。
 */
note: string, };
