// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deal } from "./Deal";
import type { SceneId } from "./SceneId";
import type { SceneKind } from "./SceneKind";
import type { Transition } from "./Transition";

export type SceneDef = { id: SceneId, kind: SceneKind, narration: string, deals: Array<Deal>, exits: Array<Transition>, };
