// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scenario } from "./Scenario";

/**
 * 開催時点のシナリオを凍結コピーしたもの。元シナリオの後編集と独立。
 */
export type ScenarioSnapshot = Scenario;
