// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDef } from "./CardDef";
import type { PhaseDef } from "./PhaseDef";
import type { ScenarioMeta } from "./ScenarioMeta";

export type Scenario = { meta: ScenarioMeta, card_defs: Array<CardDef>, phases: Array<PhaseDef>, };
