// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";
import type { ProposalId } from "./ProposalId";

export type SessionStatus = "Running" | { "Paused": { proposal: ProposalId, } } | { "Ended": Outcome };
