// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardInstance } from "./CardInstance";
import type { CardInstanceId } from "./CardInstanceId";
import type { Character } from "./Character";
import type { CharacterId } from "./CharacterId";
import type { Phase } from "./Phase";
import type { Proposal } from "./Proposal";
import type { Role } from "./Role";
import type { ScenarioSnapshot } from "./ScenarioSnapshot";
import type { SceneId } from "./SceneId";
import type { SessionStatus } from "./SessionStatus";
import type { UserId } from "./UserId";

export type Session = { scenario: ScenarioSnapshot, party: Array<Character>, status: SessionStatus, roles: { [key in UserId]: Role }, phase: Phase, scene: SceneId, hands: { [key in CharacterId]: Array<CardInstance> }, table: Array<CardInstance>, pending_proposal: Proposal | null, 
/**
 * `ProposalId`発番用の単調カウンタ。`CardInstanceId`と異なり
 * `pending_proposal`は裁定のたびに`None`へ戻る(除去が起きる)ため、
 * 現在状態からの逆算では連番の一意性を保てない。そこで別途カウンタを持つ
 * (domain-model.md「提案と裁定」参照)。
 */
proposal_seq: bigint, 
/**
 * `CardInstanceId`発番用の単調カウンタ。カードは除去されうるため、
 * `hands`+`table`の現在の総数からの逆算では一意性を保てない
 * (`proposal_seq`と同じ理由。domain-model.md「カードの消費・除去」参照)。
 * 除去してもID空間は消費されたままとし、巻き戻さない。
 */
card_instance_seq: number, 
/**
 * 現在のシーンが`SceneEntered`で配ったカードのうち、まだ`hands`にある
 * ものの一覧(シーン離脱時クリーンアップの対象候補。domain-model.md
 * 「カードの消費・除去」参照)。
 */
scene_local_instances: Array<CardInstanceId>, };
