// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterId } from "./CharacterId";

/**
 * 効果の対象。意味論は domain-model.md「Target の意味論」参照(2026-07-18決定):
 * - `Party` は役割参照。台本(シナリオ)執筆時点で書ける
 * - `Character` は実名参照で**上演中専用**。シナリオデータ内での使用は不正
 *   (解決不能。P2のシナリオlintで検出)
 */
export type Target = "Party" | { "Character": CharacterId };
