// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { SceneId } from "./SceneId";

/**
 * Conditionによる自動遷移。カードのGotoScene効果による遷移とは別経路。
 */
export type Transition = { condition: Condition, to: SceneId, };
