// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchError } from "./PatchError";
import type { RuleError } from "./RuleError";

/**
 * 境界越しのエラー封筒。`RuleError`/`PatchError`をそのままJSON化せず、
 * 種別を含めて包む(TS側が`kind`で確実に分岐できるようにするため。
 * wasm-boundary.md「方針4」)。TSへ渡すのみ(Rust側でデコードしないため
 * `Deserialize`は実装しない)。
 */
export type WasmError = { "kind": "rule", "error": RuleError } | { "kind": "patch", "error": PatchError } | { "kind": "decode", "error": string };
